title: Manas Goth's Blogs
description: Deep Learning, PyTorch, Transformers, LLMs, AI Engineering, and Data Science.
author: Manas Goth

url: "https://manasgoth.github.io"
baseurl: "/pytorch-essentials-blog"

theme: minima

markdown: kramdown
highlighter: rouge

plugins:

* jekyll-feed
* jekyll-seo-tag

show_excerpts: true

minima:
skin: classic

social_links:
github: ManasGoth

header_pages:

* about.md

exclude:

* notebooks/
* .ipynb_checkpoints/
* README.md

permalink: /:categories/:title/
